register_families_folder = ['./config']
mylang = "wikidata"
family = "wikidata"
# usernames['my']['my'] = u'WikidataUpdater'
usernames['my']['my'] = u'WikibaseAdmin'
password_file = "user-password.py"
minthrottle = 0
maxthrottle = 0
max_retries = 100
#verbose_output = True
